version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345678
    networks:
      - backend

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345678
      ME_CONFIG_MONGODB_URL: mongodb://root:12345678@mongo:27017/
    depends_on:
      - mongo
    networks:
      - backend

  app:
    image: gutkarsh89/testapp
    container_name: nodeapp
    ports:
      - "5050:5050"
    environment:
      - MONGO_URL=mongodb://root:12345678@mongo:27017
    depends_on:
      - mongo
    networks:
      - backend

networks:
  backend:
    driver: bridge

